nodejs:
  # Don't modify below here
  image: https://hmcts.azurecr.io/hmcts/et-syr:latest
  ingressHost: 
  devmemoryLimits: 1024Mi
  devmemoryRequests: 512Mi
  environment:
    OAUTH_CLIENT_REDIRECT: https:///oauth2/callback
    REDIS_SECONDARY_HOST: 'et-managed-redis-aat.uksouth.redis.azure.net'
    REDIS_SECONDARY_PORT: '10000'
  keyVaults:
    et:
      resourceGroup: et
      secrets:
        - AppInsightsInstrumentationKey
        - idam-secret
        - et-redis-access-key
        - et-managed-redis-access-key
        - et-session-secret
        - os-places-token
        - pcq-token-key
        - launch-darkly-sdk-key
        - s2s-secret-syr
idam-pr:
  enabled: false
