java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
    apim:
      secrets:
        - name: marketplace-POSTGRES-USER
          alias: POSTGRES_USER
        - name: marketplace-POSTGRES-PASS
          alias: POSTGRES_PASS
        - name: marketplace-POSTGRES-HOST
          alias: POSTGRES_HOST
        - name: marketplace-POSTGRES-PORT
          alias: POSTGRES_PORT
        - name: marketplace-POSTGRES-DATABASE
          alias: POSTGRES_DATABASE
