# Don't modify this file, it is only needed for the pipeline to set the image and ingressHost
java:
  image: https://hmcts.azurecr.io/hmcts/apim-marketplace:latest
  ingressHost: apim-marketplace-staging.aat.platform.hmcts.net
  keyVaults:
    apim:
      secrets:
        - name: marketplace-POSTGRES-USER
          alias: POSTGRES_USER
        - name: marketplace-POSTGRES-PASS
          alias: POSTGRES_PASS
        - name: marketplace-POSTGRES-HOST
          alias: POSTGRES_HOST
        - name: marketplace-POSTGRES-PORT
          alias: POSTGRES_PORT
        - name: marketplace-POSTGRES-DATABASE
          alias: POSTGRES_DATABASE
