java:
  applicationPort: 8080
  image: 'hmctsprod.azurecr.io/apim/marketplace:latest'
  ingressHost: apim-marketplace-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: apim
  environment:
    APPLICATIONINSIGHTS_ENABLED: "false"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=00000000-0000-0000-0000-000000000000"
  keyVaults:
    apim:
      secrets:
        - name: marketplace-POSTGRES-USER
          alias: POSTGRES_USER
        - name: marketplace-POSTGRES-PASS
          alias: POSTGRES_PASS
        - name: marketplace-POSTGRES-HOST
          alias: POSTGRES_HOST
        - name: marketplace-POSTGRES-PORT
          alias: POSTGRES_PORT
        - name: marketplace-POSTGRES-DATABASE
          alias: POSTGRES_DATABASE
