apiVersion: v2
appVersion: "1.0"
description: A Helm chart for pre-api App
name: pre-api
home: https://github.com/hmcts/pre-api
version: 0.0.101
maintainers:
  - name: HMCTS pre team
dependencies:
  - name: java
    version: 6.1.1
    repository: oci://hmctsprod.azurecr.io/helm
    condition: java.enabled
  - name: job
    version: 2.2.2
    repository: oci://hmctsprod.azurecr.io/helm
    condition: job.enabled
