python:
  applicationPort: 8000
  image: 'hmctsprod.azurecr.io/labs/connorokane-kainos:latest'
  ingressHost: labs-connorokane-kainos-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  environment:
  # keyVaults:
  #   labs:
  #     secrets:
  #       - name: AppInsightsConnectionString
  #         alias: APPLICATIONINSIGHTS_CONNECTION_STRING
  # postgresql:
  #   enabled: true
