job:
  image: hmctsprod.azurecr.io/fact/cron-trigger:latest
  aadIdentityName: fact
  keyVaults:
    fact:
      secrets:
        - name: app-insights-connection-string-ai
          alias: app-insights-connection-string
        - name: storage-account-connection-string
          alias: STORAGE_ACCOUNT_CONNECTION_STRING
    fact-kv:
      secrets:
        - name: fact-cron-trigger-app-reg-id
          alias: AZURE_CLIENT_ID
        - name: bstrap-cron-trigger-client-secret
          alias: AZURE_CLIENT_SECRET
        - name: api-app-reg-id
          alias: AZURE_APP_REGISTRATION_ID
        - name: bstrap-slack-token
          alias: SLACK_TOKEN
        - name: bstrap-slack-channel-id
          alias: SLACK_CHANNEL_ID
  environment:
    FACT_API_URL: "http://fact-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    FACT_DATA_API_URL: "https://fact-data-api.{{ .Values.global.environment }}.platform.hmcts.net"
  global:
    jobKind: CronJob
    enableKeyVaults: true
