apiVersion: v2
name: sscs-tribunals-api
home: https://github.com/hmcts/sscs-tribunals-case-api
version: 0.0.236
description: SSCS Tribunals Case API
annotations:
  hmcts.github.io/skip-publish: postgresql,job,xui-webapp,ccd,sscs-tribunals-frontend,hmcts-redis,em-ccdorc,em-stitching,ccd-case-document-am-api,servicebus,aac-manage-case-assignment,am-org-role-mapping-service,camunda-bpm,wa-task-management-api,wa-task-monitor,wa-case-event-handler,wa-workflow-api,wa-initiation-batch,wa-reconfiguration-batch,wa-termination-batch,wa-message-cron-service,ccd-message-publisher,sscs-cron-trigger,ccd-def-cleanup
maintainers:
- name: HMCTS SSCS Team
dependencies:
- name: java
  version: 5.3.0
  repository: oci://hmctsprod.azurecr.io/helm
  condition: java.enabled
- name: servicebus
  version: 1.2.2
  repository: oci://hmctsprod.azurecr.io/helm
  condition: servicebus.enabled
  alias: hmcsb
