java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
    ethos-shared:
      resourceGroup: ethos
      secrets:
        - name: app-insights-connection-string
          alias: app-insights-connection-string
        - name: ecm-consumer-s2s-key
          alias: ECM_CONSUMER_S2S_KEY
        - name: caseworker-user-name
          alias: CASEWORKER_USER_NAME
        - name: caseworker-password
          alias: CASEWORKER_PASSWORD
        - name: idam-client-secret
          alias: IDAM_CLIENT_SECRET
