java:
  applicationPort: 4550
  image: 'hmctsprod.azurecr.io/rota/optimiser:latest'
  ingressHost: rota-optimiser-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: rota
  keyVaults:
    rota-shared:
      resourceGroup: rota-shared-infra
      secrets:
        - name: application-insights-connection-string
          alias: app-insights-connection-string
        - name: postgresql-fqdn
          alias: postgresql-fqdn
        - name: postgresql-admin-username
          alias: postgresql-admin-username
        - name: postgresql-admin-password
          alias: postgresql-admin-password
  environment:
    ROTA_OPTIMISER_WORKER_LEASE_DURATION: PT2M
    ROTA_OPTIMISER_WORKER_RECOVERY_INTERVAL: PT30S
    ROTA_OPTIMISER_WORKER_MAX_ATTEMPTS: 3
    ROTA_OPTIMISER_WORKER_REQUIRE_LEASE_TOKEN: false
