java:
  applicationPort: 8081
  image: 'hmctsprod.azurecr.io/snl/snl-backend:latest'
  ingressHost: snl-backend.{{ .Values.global.environment }}.platform.hmcts.net
  aadIdentityName: snl
#  Uncomment once the vault containing the app insights key has been set up
#  keyVaults:
#    snl:
#      secrets:
#        - name: AppInsightsInstrumentationKey
#          alias: azure.application-insights.instrumentation-key
#        - name: app-insights-connection-string
#          alias: app-insights-connection-string
  environment:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: /opt/app/applicationinsights.json
    APPLICATIONINSIGHTS_ROLE_NAME: snl-backend
