nodejs:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
    hmc:
      secrets:
        - AppInsightsInstrumentationKey
        - hmc-admin-ui-session-secret
        - hmc-admin-ui-client-secret
        - hmc-admin-ui-s2s-secret
  environment:
    REDIS_ENABLED: false
