apiVersion: v2
appVersion: '1.0'
description: A Helm chart for wa-reporting-frontend App
name: wa-reporting-frontend
home: https://github.com/hmcts/wa-reporting-frontend
version: 0.0.24
dependencies:
  - name: nodejs
    version: 3.2.1
    repository: 'oci://hmctsprod.azurecr.io/helm'
  - name: hmcts-redis
    version: 0.8.0
    repository: 'oci://hmctsprod.azurecr.io/helm'
    condition: hmcts-redis.enabled
