name: apple-recipe-backend
apiVersion: v2
home: https://github.com/hmcts/sds-toffee-recipes-service
version: 0.2.24
description: This is for Jenkins pipeline tests of toffee /apple app.
maintainers:
  - name: HMCTS Platform Operations Team
dependencies:
  - name: java
    version: 5.3.0
    repository: oci://hmctsprod.azurecr.io/helm
