nodejs:
  ingressAnnotations:
    external-dns.alpha.kubernetes.io/exclude: 'true'
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  devmemoryRequests: 512Mi
  devmemoryLimits: 1024Mi
  environment:
    SSO_CALLBACK_BASE_URL: http://localhost:3100
    SSO_FUNCTIONAL_DISPLAY_NAME: Functional domain-routing test
    SSO_FUNCTIONAL_DOMAIN: functional.test
    SSO_FUNCTIONAL_LOGIN_URL: /auth/functional-test-sso/login
