java:
  image: 'hmctspublic.azurecr.io/et/et-msg-handler:latest'
  applicationPort: 8085
  ingressHost: et-msg-handler-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: et
  environment:
    REFORM_TEAM: et
    REFORM_SERVICE_NAME: et-msg-handler
    REFORM_SERVICE_TYPE: java
    REFORM_ENVIRONMENT: preview
    ROOT_LOGGING_LEVEL: INFO
    LOG_OUTPUT: single
    ET_MSG_HANDLER_URL: "http://et-msg-handler-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    IDAM_API_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
    IDAM_API_JWK_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net/jwks"
    IDAM_API_OIDC_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net/o/token"
    IDAM_CLIENT_REDIRECT_URL: "https://et-msg-handler-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/oauth2redirect"
    SERVICE_AUTH_PROVIDER_URL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    CCD_DATA_STORE_API_URL: "http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    MICRO_SERVICE: "et_msg_handler"
    CCD_GATEWAY_BASE_URL: "https://manage-case.{{ .Values.global.environment }}.platform.hmcts.net"
