apiVersion: v2
name: et-cos
home: https://github.com/hmcts/et-ccd-callbacks
version: 0.0.78
description: HMCTS Employment Tribunals CCD Callbacks service
maintainers:
- name: HMCTS Employment Tribunals Team
annotations:
  hmcts.github.io/skip-publish: ccd, xui-webapp, idam-pr, et-sya, et-syr, aac-manage-case-assignment, xui-mo-webapp, xui-ao-webapp, wa, servicebus, ccd-message-publisher, ccd-case-document-am-api, am-org-role-mapping-service, rd-caseworker-ref-api, postgresql, rd-professional-api, rd-user-profile-api, rd-judicial-api, rd-judicial-data-load, em-ccdorc
dependencies:
- name: java
  version: 6.1.1
  repository: oci://hmctsprod.azurecr.io/helm
  condition: java.enabled
