java:
  image: https://hmcts.azurecr.io/hmcts/et-cos:latest
  ingressHost: 
  enabled: true

ccd:
  enabled: false
xui-webapp:
  enabled: false
idam-pr:
  enabled: false
et-sya:
  enabled: false
et-syr:
  enabled: false
## et-sya-api to be removed once repo merge has been completed
et-sya-api:
  enabled: false
wa:
  enabled: false
servicebus:
  enabled: false
ccd-message-publisher:
  enabled: false
aac-manage-case-assignment:
  enabled: false
am-org-role-mapping-service:
  enabled: false
em-ccdorc:
  enabled: false
et-migration:
  enabled: false
rd-judicial-data-load:
  enabled: false
rd-judicial-api:
  enabled: false
rd-professional-api:
  enabled: false
rd-user-profile-api:
  enabled: false
rd-caseworker-ref-api:
  enabled: false
ccd-case-document-am-api:
  enabled: false
xui-mo-webapp:
  enabled: false
xui-ao-webapp:
  enabled: false