nodejs:
  # Don't modify below here
  image: https://hmcts.azurecr.io/hmcts/appreg-frontend:latest
  ingressHost: 
  environment:
    APPREG_API_BASE_URL: https://appreg-api.staging.platform.hmcts.net
