apiVersion: v2
appVersion: "1.0"
description: A Helm chart for darts-proxy App
name: darts-proxy
home: https://github.com/hmcts/darts-proxy
version: 0.0.8
maintainers:
  - name: HMCTS darts proxy team
dependencies:
  - name: java
    version: 6.0.0
    repository: 'oci://hmctsprod.azurecr.io/helm'
