apiVersion: v2
appVersion: "1.0"
description: A Helm chart for pcs-api App
name: pcs-api
home: https://github.com/hmcts/pcs-api
version: 0.0.92
maintainers:
  - name: HMCTS pcs team
dependencies:
  - name: java
    version: 5.3.0
    repository: 'oci://hmctsprod.azurecr.io/helm'
  - name: servicebus
    version: 1.2.2
    repository: 'oci://hmctsprod.azurecr.io/helm'
    condition: servicebus.enabled
  - name: ccd
    version: 9.2.3
    repository: 'oci://hmctsprod.azurecr.io/helm'
    condition: ccd.enabled
  - name: xui-webapp
    version: 1.0.45
    repository: 'oci://hmctsprod.azurecr.io/helm'
    condition: xui-webapp.enabled
  - name: xui-mo-webapp
    version: 1.1.26
    repository: 'oci://hmctsprod.azurecr.io/helm'
    condition: xui-mo-webapp.enabled
  - name: postgresql
    version: 1.1.1
    repository: 'oci://hmctsprod.azurecr.io/helm'
    condition: postgresql.enabled
  - name: wiremock
    version: 0.0.7
    repository: 'oci://hmctsprod.azurecr.io/helm'
    condition: wiremock.enabled
  - name: ccd-case-document-am-api
    version: 1.7.19
    repository: 'oci://hmctsprod.azurecr.io/helm'
    condition: ccd-case-document-am-api.enabled
  - name: aac-manage-case-assignment
    version: ~0.2.20
    repository: 'oci://hmctsprod.azurecr.io/helm'
    condition: aac-manage-case-assignment.enabled
  - name: am-org-role-mapping-service
    version: 0.0.77
    repository: 'oci://hmctsprod.azurecr.io/helm'
    condition: am-org-role-mapping-service.enabled
#    Work Allocation
  - name: wa
    version: ~1.1.0
    repository: 'oci://hmctsprod.azurecr.io/helm'
    condition: wa.enabled
