ccd:
  elasticsearch:
    minimumMasterNodes: 1
    persistence:
      enabled: false
    volumeClaimTemplate:
      resources:
        requests:
          storage: 500Mi
      storageClassName: managed-lrs
