java:
  environment:
    CAMUNDA_BASE_URL: http://pcs-api-pr-${CHANGE_ID}-camunda/engine-rest

postgresql:
  enabled: true
  flexibleserver: pcs-preview
  setup:
    databases:
      - name: "pr-${CHANGE_ID}-data-store"
      - name: "pr-${CHANGE_ID}-definition-store"
      - name: "pr-${CHANGE_ID}-pcs"
      - name: "pr-${CHANGE_ID}-camunda"
      - name: "pr-${CHANGE_ID}-cft_task_db"
      - name: "pr-${CHANGE_ID}-wa_workflow_api"

global:
  postgresUsername: hmcts
  postgresSecret: postgres
  postgresHost: "pcs-preview.postgres.database.azure.com"
  postgresHostname: "pcs-preview.postgres.database.azure.com"
  databaseNamePrefix: "pr-${CHANGE_ID}-"

wa:
  enabled: true

  camunda-bpm:
    java:
      image: hmctsprod.azurecr.io/camunda/bpm:latest
      environment:
        SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "4"
        SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: "1"
        CAMUNDA_BPM_JOB_EXECUTION_CORE_POOL_SIZE: "1"
        CAMUNDA_BPM_JOB_EXECUTION_MAX_POOL_SIZE: "2"

  wa-task-management-api:
    java:
      ingressHost: wa-task-management-api-${SERVICE_FQDN}
      environment:
        ALLOWED_CASE_TYPES: pcs
        ALLOWED_JURISDICTIONS: pcs
        ROLE_ASSIGNMENT_URL: http://am-role-assignment-service-aat.service.core-compute-aat.internal
        SPRING_DATASOURCE_MAXIMUM_POOL_SIZE: "4"
        SPRING_DATASOURCE_MINIMUM_IDLE: "1"
      keyVaults:
        wa:
          secrets:
            - name: app-insights-connection-string
              alias: app-insights-connection-string
            - name: wa-system-username
              alias: WA_SYSTEM_USERNAME
            - name: wa-system-password
              alias: WA_SYSTEM_PASSWORD
            - name: wa-idam-client-secret
              alias: WA_IDAM_CLIENT_SECRET
            - name: s2s-secret-task-management-api
              alias: S2S_SECRET_TASK_MANAGEMENT_API
            - name: ld-secret
              alias: LAUNCH_DARKLY_SDK_KEY

  wa-task-monitor:
    java:
      ingressHost: wa-task-monitor-${SERVICE_FQDN}
      keyVaults:
        wa:
          secrets:
            - name: app-insights-connection-string
              alias: app-insights-connection-string
            - name: s2s-secret-task-monitor
              alias: S2S_SECRET_TASK_MONITOR
            - name: wa-system-username
              alias: WA_SYSTEM_USERNAME
            - name: wa-system-password
              alias: WA_SYSTEM_PASSWORD
            - name: wa-idam-client-secret
              alias: WA_IDAM_CLIENT_SECRET

  wa-workflow-api:
    java:
      environment:
        DB_READER_USERNAME: "hmcts"
        SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "4"
        SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: "1"
      keyVaults:
        wa:
          secrets:
            - name: app-insights-connection-string
              alias: app-insights-connection-string
            - name: s2s-secret-workflow-api
              alias: S2S_SECRET_WORKFLOW_API
            - name: ld-secret
              alias: LAUNCH_DARKLY_SDK_KEY

  wa-message-cron-service:
    job:
      schedule: "*/1 * * * *"

  wa-initiation-batch:
    job:
      schedule: "*/1 * * * *"
      disableActiveClusterCheck: true
      suspend: false

  wa-reconfiguration-batch:
    job:
      schedule: "*/1 * * * *"

  wa-termination-batch:
    job:
      schedule: "*/1 * * * *"
      disableActiveClusterCheck: true
      suspend: false

  #disable wa db as we are using the postgres flexible server
  wa:
    postgresql:
      enabled: false
    eventHandler:
      enabled: false
    messageCron:
      enabled: false

xui-webapp:
  nodejs:
    environment:
      SERVICES_WA_WORKFLOW_API_URL: http://{{ .Release.Name }}-wa-workflow-api
      HEALTH_WORK_ALLOCATION_TASK_API: http://{{ .Release.Name }}-wa-task-management-api/health
      SERVICES_WORK_ALLOCATION_TASK_API: http://{{ .Release.Name }}-wa-task-management-api
      WA_SUPPORTED_JURISDICTIONS: PCS
