# The pipeline's temporary `-staging` release. The persistent AAT release is Flux's, from values.yaml.
nodejs:
  saEnabled: true
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    AUTH_DISABLED: "true"
    VIRTUAL_AGENTS_ENABLED: "false"
