nodejs:
  applicationPort: 3100
  aadIdentityName: finrem
  ingressHost: finrem-citizen-ui.{{ .Values.global.environment }}.platform.hmcts.net
  image: 'hmctspublic.azurecr.io/finrem/citizen-ui:latest'
  memoryRequests: 1024Mi
  cpuRequests: 2500m
  memoryLimits: 2048Mi
  cpuLimits: 2500m
  readinessDelay: 130
  livenessDelay: 130

  keyVaults:
    finrem:
      secrets:
        - name: app-insights-connection-string
          alias: app-insights-connection-string
        - name: finrem-citizen-ui-idam-client-secret
          alias: finrem-citizen-ui-idam-client-secret

  autoscaling:
    enabled: true
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80

  environment:
    IDAM_WEB_URL: https://hmcts-access.{{ .Values.global.environment }}.platform.hmcts.net/login
    IDAM_API_URL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net/o/token
    IDAM_CLIENT_ID: finrem-citizen-ui
    IDAM_END_SESSION_URL: https://hmcts-access.{{ .Values.global.environment }}.platform.hmcts.net/o/endSession
    REDIS_EXPIRE_IN_DAYS: 180
    SECURE_COOKIE: 'true'

redis:
  enabled: false
