global:
  security:
    allowInsecureImages: true
nodejs:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  devcpuRequests: 250m
  devmemoryRequests: 1Gi
  devcpuLimits: 1
  devmemoryLimits: 1Gi
  readinessDelay: 45
  readinessTimeout: 5
  readinessPeriod: 15
  livenessDelay: 45
  livenessTimeout: 5
  livenessPeriod: 15

  environment:
    NODE_ENV: preview
    IDAM_TOKEN_CACHE: true
    ENABLE_TEST_SUPPORT_ROUTES: 'true'
    OAUTH_CALLBACK_URL: 'https://${SERVICE_FQDN}/oauth2/callback'
    IDAM_WEB_URL: https://hmcts-access.aat.platform.hmcts.net/o/authorize
    IDAM_TOKEN_URL: https://idam-api.aat.platform.hmcts.net/o/token
    REDIS_CONNECTION_STRING: 'redis://{{ .Release.Name }}-redis-master:6379'
    CCD_URL: 'http://ccd-data-store-api-aat.service.core-compute-aat.internal'
    CASE_DOCUMENT_MANAGEMENT_URL: 'http://ccd-case-document-am-api-aat.service.core-compute-aat.internal'


redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: false
  image:
    registry: hmctsprod.azurecr.io
    repository: imported/bitnami/redis
