global:
  security:
    allowInsecureImages: true
nodejs:
  environment:
    OAUTH_CALLBACK_URL: 'https:///oauth2/callback'
    IDAM_CLIENT_ID: finrem-citizen-ui

    # AAT IDAM endpoints
    IDAM_WEB_URL: https://hmcts-access.aat.platform.hmcts.net/login
    IDAM_END_SESSION_URL: https://hmcts-access.aat.platform.hmcts.net/o/endSession
    IDAM_API_URL: https://idam-api.aat.platform.hmcts.net/o/token

  # Don't modify below here
  image: https://hmcts.azurecr.io/hmcts/finrem-citizen-ui:latest
  ingressHost: 

  keyVaults:
    finrem:
      secrets:
        - name: finrem-citizen-ui-idam-client-secret
          alias: finrem-citizen-ui-idam-client-secret
        - name: app-insights-connection-string
          alias: app-insights-connection-string
