global:
  security:
    allowInsecureImages: true
nodejs:
  environment:
    NODE_ENV: aat
    OAUTH_CALLBACK_URL: 'https://${SERVICE_FQDN}/oauth2/callback'
    ENABLE_TEST_SUPPORT_ROUTES: 'true'
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  devmemoryRequests: 1Gi
  devmemoryLimits: 2Gi
