java:
  applicationPort: 4550
  image: 'hmctsprod.azurecr.io/pt/pt-api:latest'
  ingressHost: pt-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: pt
#  Uncomment once the vault containing the app insights key has been set up
#  keyVaults:
#    pt:
#      secrets:
#        - name: AppInsightsInstrumentationKey
#          alias: azure.application-insights.instrumentation-key
  environment:
