java:
  applicationPort: 4550
  image: 'hmctsprod.azurecr.io/pt/pt-api:latest'
  ingressHost: pt-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: pt
  keyVaults:
    pt:
       secrets:
         - name: app-insights-connection-string
  environment:
