global:
  ccdApiGatewayIngress: http://${SERVICE_NAME}-ccd-api-gw
  ccdDefinitionStoreUrl: http://${SERVICE_NAME}-ccd-definition-store
  ccdUserProfileUrl: http://ccd-user-profile-api-aat.service.core-compute-aat.internal
  dmStoreUrl: http://dm-store-aat.service.core-compute-aat.internal
  idamApiUrl: https://idam-api.aat.platform.hmcts.net
  idamWebUrl: https://idam-web-public.aat.platform.hmcts.net
  s2sUrl: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
  postgresSecret: ${SERVICE_NAME}-postgresql

java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
    pt-kv:
      secrets:
         - name: app-insights-connection-string
         - name: pt-api-s2s-secret
           alias: PT_API_S2S_SECRET
  environment:
    PT_DB_HOST: "{{ .Release.Name }}-postgresql"
    PT_DB_USER_NAME: "{{ .Values.postgresql.auth.username}}"
    PT_DB_NAME: "{{ .Values.postgresql.auth.database}}"
  secrets:
    PT_DB_PASSWORD:
      secretRef: "{{ .Values.global.postgresSecret }}"
      key: password
  postgresql:
    enabled: true
    image:
      tag: "16.0.0"
