java:
  applicationPort: 4550
  image: 'hmctsprod.azurecr.io/rota/frontend:latest'
  ingressHost: rota-frontend-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: rota
#  Uncomment once the vault containing the app insights key has been set up
#  keyVaults:
#    rota:
#      secrets:
#        - name: AppInsightsInstrumentationKey
#          alias: azure.application-insights.instrumentation-key
  environment:
