java:
  # Don't modify below here
  image: https://hmcts.azurecr.io/hmcts/recipes-backend:latest
  ingressHost: 
  environment:
    POSTGRES_SSL_MODE: require
  keyVaults:
    "recipes-sds-kv":
      secrets:
        - name: recipes-backend-POSTGRES-DATABASE
          alias: POSTGRES_DATABASE
        - name: recipes-backend-POSTGRES-HOST
          alias: POSTGRES_HOST
        - name: recipes-backend-POSTGRES-USER
          alias: POSTGRES_USER
        - name: recipes-backend-POSTGRES-PASS
          alias: POSTGRES_PASSWORD
