apiVersion: v2
appVersion: '1.0'
description: A Helm chart for apim-marketplace-web App
name: apim-marketplace-web
home: https://github.com/hmcts/web-api-marketplace
version: 0.0.3
maintainers:
  - name: DTS API Marketplace
dependencies:
  - name: nodejs
    version: 3.2.1
    repository: oci://hmctsprod.azurecr.io/helm
