apiVersion: v2
appVersion: "1.0"
description: Collects and grades evidence of software delivery practice from GitHub
name: dtsse-github-metrics
home: https://github.com/hmcts/dtsse-github-metrics
version: 0.0.3
dependencies:
  - name: nodejs
    version: 3.2.1
    repository: "oci://hmctsprod.azurecr.io/helm"
  - name: job
    version: 2.2.1
    repository: "oci://hmctsprod.azurecr.io/helm"
    condition: job.enabled
  - name: postgresql
    version: 1.1.1
    repository: "oci://hmctsprod.azurecr.io/helm"
    condition: postgresql.enabled
