apiVersion: v2
appVersion: "1.1"
description: A Helm chart for AppReg API
name: appreg-api
home: https://github.com/hmcts/appreg-api
version: 0.0.6
maintainers:
  - name: HMCTS AppReg Team
dependencies:
  - name: java
    version: 5.3.0
    repository: 'oci://hmctsprod.azurecr.io/helm'
  - name: postgresql
    version: 1.1.1
    repository: 'oci://hmctsprod.azurecr.io/helm'
    condition: postgresql.enabled
  - name: appreg-frontend
    version: 0.0.15
    repository: 'oci://hmctsprod.azurecr.io/helm'
    condition: appreg-frontend.enabled
