java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  devmemoryLimits: "3Gi"
  environment:
    POSTGRES_USER: "hmcts"
    POSTGRES_HOST: "appreg-dev.postgres.database.azure.com"
    # The profile that dictates what data is inserted
    SPRING_PROFILES_ACTIVE: functional
    POSTGRES_DATABASE: "pr-${CHANGE_ID}-appreg"
  secrets:
    POSTGRES_PASS:
      secretRef: "postgres"
      key: PASSWORD
      disabled: false

# Launch the database that this PR will be working against
postgresql:
  enabled: true
  flexibleserver: "appreg-dev"
  setup:
    databases:
      - name: "pr-${CHANGE_ID}-appreg"

# This is needed if want to launch the portal along side this pr
appreg-frontend:
  enabled: ${DEV_ENABLE_PORTAL}
  nodejs:
    releaseNameOverride: '{{ .Release.Name }}-portal'
    applicationPort: 4000
    # This is needed if want to launch a specific version of the portal along side this pr, otherwise it will use the latest image
    image: 'sdshmctspublic.azurecr.io/appreg/frontend:${DEV_PORTAL_IMAGE}'
    ingressHost: "appreg-frontend-with-api-pr-${CHANGE_ID}.dev.platform.hmcts.net"
    aadIdentityName: appreg
    environment:
      ALLOW_CONFIG_MUTATIONS: true
      NODE_ENV: 'production'
      TESTVAR: 'testvalue'
      LOG_LEVEL: 'DEBUG'
      APPREG_API_BASE_URL: "https://appreg-api-pr-${CHANGE_ID}.dev.platform.hmcts.net"
    keyVaults:
      appreg:
        secrets:
          - name: app-insights-connection-string
            alias: app-insights-connection-string-fe
          - name: azure-tenant-id
            alias: azure-tenant-id-fe
          - name: azure-client-secret
            alias: azure-client-secret-fe
          - name: azure-app-id
            alias: azure-app-id-fe
          - name: redis-access-key
            alias: redis-access-key
          - name: test-user1-email
            alias: TEST-USER1-EMAIL
          - name: test-user2-email
            alias: TEST-USER2-EMAIL
          - name: test-user3-email
            alias: TEST-USER3-EMAIL
          - name: test-admin1-email
            alias: TEST-ADMIN1-EMAIL
          - name: test-admin2-email
            alias: TEST-ADMIN2-EMAIL
          - name: test-admin3-email
            alias: TEST-ADMIN3-EMAIL
          - name: test-users-password
            alias: TEST-USERS-PASSWORD
