java:
  applicationPort: 8080
  image: 'hmctssbox.azurecr.io/labs/beardfacekainos:latest'
  ingressHost: labs-beardfacekainos-staging.{{ .Values.global.environment }}.platform.hmcts.net
  aadIdentityName: labs
  environment:
