java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    OPAL_USER_SERVICE_API_URL: https://opal-user-service.staging.platform.hmcts.net
    TESTING_SUPPORT_ENDPOINTS_ENABLED: true
    FLYWAY_LOCATIONS: classpath:db/migration/ddl, classpath:db/migration/data/allEnvs, classpath:db/migration/data/nle, classpath:db/migration/data/stg

bt-eckoh-report:
  releaseNameOverride: opal-file-handler-service-stg-bt-eckoh-report
  image: ${IMAGE_NAME}
  environment:
    OPAL_FRONTEND_URL: https://opal-frontend-staging.staging.apps.hmcts.net
    TESTING_SUPPORT_ENDPOINTS_ENABLED: false
    FLYWAY_LOCATIONS: classpath:db/migration/ddl, classpath:db/migration/data/allEnvs, classpath:db/migration/data/nle, classpath:db/migration/data/stg

caps-report:
  releaseNameOverride: opal-file-handler-service-stg-caps-report
  image: ${IMAGE_NAME}
  environment:
    OPAL_FRONTEND_URL: https://opal-frontend-staging.staging.apps.hmcts.net
    TESTING_SUPPORT_ENDPOINTS_ENABLED: false
    FLYWAY_LOCATIONS: classpath:db/migration/ddl, classpath:db/migration/data/allEnvs, classpath:db/migration/data/nle, classpath:db/migration/data/stg

natwest-transfer:
  releaseNameOverride: opal-file-handler-service-stg-natwest-transfer
  image: ${IMAGE_NAME}
  environment:
    OPAL_FRONTEND_URL: https://opal-frontend-staging.staging.apps.hmcts.net
    TESTING_SUPPORT_ENDPOINTS_ENABLED: false
    FLYWAY_LOCATIONS: classpath:db/migration/ddl, classpath:db/migration/data/allEnvs, classpath:db/migration/data/nle, classpath:db/migration/data/stg

allpay-file-transfer:
  releaseNameOverride: opal-file-handler-service-stg-allpay-file-transfer
  image: ${IMAGE_NAME}
  environment:
    OPAL_FRONTEND_URL: https://opal-frontend-staging.staging.apps.hmcts.net
    TESTING_SUPPORT_ENDPOINTS_ENABLED: false
    FLYWAY_LOCATIONS: classpath:db/migration/ddl, classpath:db/migration/data/allEnvs, classpath:db/migration/data/nle, classpath:db/migration/data/stg

barclaycard-transfer:
  releaseNameOverride: opal-file-handler-service-stg-barclaycard-transfer
  image: ${IMAGE_NAME}
  environment:
    OPAL_FRONTEND_URL: https://opal-frontend-staging.staging.apps.hmcts.net
    TESTING_SUPPORT_ENDPOINTS_ENABLED: false
    FLYWAY_LOCATIONS: classpath:db/migration/ddl, classpath:db/migration/data/allEnvs, classpath:db/migration/data/nle, classpath:db/migration/data/stg

bt-eckoh-transfer:
  releaseNameOverride: opal-file-handler-service-stg-bt-eckoh-transfer
  image: ${IMAGE_NAME}
  environment:
    OPAL_FRONTEND_URL: https://opal-frontend-staging.staging.apps.hmcts.net
    TESTING_SUPPORT_ENDPOINTS_ENABLED: false
    FLYWAY_LOCATIONS: classpath:db/migration/ddl, classpath:db/migration/data/allEnvs, classpath:db/migration/data/nle, classpath:db/migration/data/stg

dwp-transfer:
  releaseNameOverride: opal-file-handler-service-stg-dwp-transfer
  image: ${IMAGE_NAME}
  environment:
    OPAL_FRONTEND_URL: https://opal-frontend-staging.staging.apps.hmcts.net
    TESTING_SUPPORT_ENDPOINTS_ENABLED: false
    FLYWAY_LOCATIONS: classpath:db/migration/ddl, classpath:db/migration/data/allEnvs, classpath:db/migration/data/nle, classpath:db/migration/data/stg

jacobs-transfer:
  releaseNameOverride: opal-file-handler-service-stg-jacobs-transfer
  image: ${IMAGE_NAME}
  environment:
    OPAL_FRONTEND_URL: https://opal-frontend-staging.staging.apps.hmcts.net
    TESTING_SUPPORT_ENDPOINTS_ENABLED: false
    FLYWAY_LOCATIONS: classpath:db/migration/ddl, classpath:db/migration/data/allEnvs, classpath:db/migration/data/nle, classpath:db/migration/data/stg

cder-transfer:
  releaseNameOverride: opal-file-handler-service-stg-cder-transfer
  image: ${IMAGE_NAME}
  environment:
    OPAL_FRONTEND_URL: https://opal-frontend-staging.staging.apps.hmcts.net
    TESTING_SUPPORT_ENDPOINTS_ENABLED: false
    FLYWAY_LOCATIONS: classpath:db/migration/ddl, classpath:db/migration/data/allEnvs, classpath:db/migration/data/nle, classpath:db/migration/data/stg

marston-transfer:
  releaseNameOverride: opal-file-handler-service-stg-marston-transfer
  image: ${IMAGE_NAME}
  environment:
    OPAL_FRONTEND_URL: https://opal-frontend-staging.staging.apps.hmcts.net
    TESTING_SUPPORT_ENDPOINTS_ENABLED: false
    FLYWAY_LOCATIONS: classpath:db/migration/ddl, classpath:db/migration/data/allEnvs, classpath:db/migration/data/nle, classpath:db/migration/data/stg