# Don't modify this file, it is only needed for the pipeline to set the image and ingressHost
python:
  image: https://hmcts.azurecr.io/hmcts/plum-fastapi-backend:latest
  ingressHost: 
  environment:
    RECIPES_SERVICE_URL: http://plum-recipe-backend-sandbox.service.core-compute-sandbox.internal
